### ISSUE TITLE
Update ReadMe Landing Picture

### ISSUE THREAD

**Issue by Chizaruu** [Chizaruu/morse-code-translator#11]

**Comment by ControlAltTea** [comment]
Hi I noticed your contribution request on first good issue. I saw that you were interested in getting sound effects working each time a user types. I've done this exact operation but with instruments (see my instruments kit repo if curious). I have cloned your repo to play with it, however, I am having difficulty running it. If you are open to me contributing, I would like to contribute but may need some assistance better understanding how to run the app on browser for testing. Please let me know if that is possible.

**Comment by Chizaruu** [comment]
@ControlAltTea 

Ah, sorry, I think you misunderstood one of the issues 😅 I left a bug that allowed the user to open a new Audio instance with each button press regardless of whether or not there is an instance currently playing.

I created the project using React, so you would need to install npm to install the packages/modules required through the package,json, and run the project.
